### ISSUE TITLE
Weapon encumbrance

### ISSUE THREAD

**Issue by joesinghaus** [Karlinator/roll20-character-sheets#10]
There's several ways of doing weapon encumbrance:
1) For each weapon, add a linked field above the rest of the gear where you can set encumbrance and readied/stowed/other status. Pro: everything that affects encumbrance is in one place. Con: It's not in the same place as the weapon itself. <- (my personal favourite)
2) Set Enc and status directly on the weapon. Pro: everything about a weapon is in the same place. Con: stuff that affects encumbrance is spread all over the sheet.
3) Both 1) and 2). Pro: combined Pros of 1) and 2). Con: having linked fields in two different places might be confusing.
4) Both 1) and 2), but make the info in the gear section read-only.

Opinions?

**Comment by PanzerUXI** [comment]
I'm with you on Option #1

**Comment by joesinghaus** [comment]
Closed by b96332e (unless we decide this solution is not good enough).
