### ISSUE TITLE
Class Ability | Populate & Export to Chat

### ISSUE THREAD

**Issue by PanzerUXI** [Karlinator/roll20-character-sheets#12]
Users have requested the ability to populate the class ability under Foci and export it like any other created foci. I think right now the word "Class Ability" is a glorified subheader, we should clean that up.

**Comment by joesinghaus** [comment]
Export to chat is clear, but what exactly do you mean by "populate"? Give it a name?

**Comment by PanzerUXI** [comment]
Give it description text. Like if Im an expert "Reroll 1 skill check per scene"

**Comment by joesinghaus** [comment]
You can do that already.

**Comment by PanzerUXI** [comment]
See you are that good, you fixed it before it was an issue.
