### ISSUE TITLE
Ammo Tracking support

### ISSUE THREAD

**Issue by PanzerUXI** [Karlinator/roll20-character-sheets#13]
We've been asked to make ammo dynamically spend itself. Possible issues if people are testing a weapon or such - probably could add a global "Track Ammo On/Off" while they are setting things up.

**Comment by joesinghaus** [comment]
Needs API script support. That having been said, it would be possible to add painless support for doing this via ChatSetAttr with a bit of extra plumbing under the hood.

**Comment by joesinghaus** [comment]
Closed by 1f29c65.
