### ISSUE TITLE
Add dedicated field to store skill points that have to be spent on psychic skills.

### ISSUE THREAD

**Issue by Karlinator** [Karlinator/roll20-character-sheets#16]

**Comment by joesinghaus** [comment]
![psionic skills](https://user-images.githubusercontent.com/18185704/40532465-cf43a620-5fff-11e8-96a2-b11e935e06e7.png)
Looks terrible, but I guess we can show it in edit mode only?

**Comment by Karlinator** [comment]
If only there were an odd number of psionic disciplines!

I didn't see this, but I've essentially implemented it just like the image above (though on the left). We could show it only in edit mode, but that's inconsistent with the other unspent skill point pool, and also just seems like weird behaviour for the sheet to have. We could make it double width, but again that's inconsistent and not that much prettier.

I'm inclined to just bite the bullet and say "that's what happens when odd numbers".

**Comment by joesinghaus** [comment]
Agreed, it works correctly now.
