### ISSUE TITLE
Transhuman and Shells (deluxe).

### ISSUE THREAD

**Issue by Karlinator** [Karlinator/roll20-character-sheets#21]

**Comment by PanzerUXI** [comment]
Oh boy.

**Comment by PanzerUXI** [comment]
@Karlinator @joesinghaus Do you think we should merge the Transhuman & Shells tickets with True AI class support? Kind of all one big enchilada.

**Comment by joesinghaus** [comment]
I'm not really knowledgeable enough about the rules to say how closely related these things are.

**Comment by Karlinator** [comment]
The whole bodyswapping mechanic is the main thing shared by AI and Transhuman characters, though I am also not that well versed in Transhuman rules. We might end up merging them, but we'll have to see when we approach actually doing it.

**Comment by Karlinator** [comment]
Some thoughts:

- A toggle in the settings to "enable shells". This should be mirrored in the sheet default settings.
- A repeating section under its own heading where one can list shells. These have three attributes (str, dex, con), basic abilities (text field) and Affinity abilities (also text field). List similar to Foci or psionic techniques.
- The Shells list has a toggle for which one is active. I don't remember if this works easily (I think it doesn't?), but that can either be solved in the worker or ignored (that is. leave it as individual checkboxes)
- The worker sets the str/dex/con_base to the values in the active shell. Since the character has no innate physical attributes separate from that of the shell there is no need to keep track of changes.

**Comment by Karlinator** [comment]
Implemented in v2.5.0
