### ISSUE TITLE
Skills quick menu (in chat) lists -1 for all skill levels

### ISSUE THREAD

**Issue by athedegaard** [Karlinator/roll20-character-sheets#23]
Hi Karlinator,

See the title: Skills quick menu (in chat) lists -1 for all skill levels, makes it difficult to figure which skill you are good at.  

Another note in the character sheet, perhaps make an easier way when you use a Quick Menu skill roll to pick the Attribute after clicking the skill (rather than put in a numeric Attribute score, which requires players to look up).

Maybe something like this: in the drop-down for # of dice, you have "2d6, 3d6, 4d6, or Ask."  Similarly, make an "Ask" option for the Attribute, would be super helpful for campaigns where skills are not tied to a specific attribute.

Thanks,
Aaron

**Comment by joesinghaus** [comment]
What exactly is the problem? The menu will update to show your current skill levels. Is is not doing that for you? Naturally, most skills will show -1 if you are not trained in them. Please provide info on what exactly is wrong here.

The "ask" option for skills already exists: in the settings, character options, "skill attribute choice", "query", will ask every time instead of taking the value selected (that one just becomes the default).

**Comment by athedegaard** [comment]
Here's what I am seeing when I open the skills Quick Menu:

![image](https://user-images.githubusercontent.com/39507122/40362937-9ddf2852-5d93-11e8-9052-afb0e2d6e461.png)

It shows up when I click on "Skills" in the upper right of the PC character sheet.  It seems to be only happening with characters that got ported over from the old character sheet.  

Oddly enough, I think this one may have resolved itself.  After going to the settings menu and changing the "Skill Attribute Choice" option to anything else, it looks like it resets the thing so that it now shows this:  
![image](https://user-images.githubusercontent.com/39507122/40363171-5a864346-5d94-11e8-8b0e-73e25f8a9f71.png)

Which seems to be working fine...  So I think there is a workaround for now, just change a setting in "Skill Attribute Choice" to whatever you want and it resolves.  Might be just a one-time annoyance.  I will monitor it during our next session to see if it's cleared up.  Thanks!

**Comment by joesinghaus** [comment]
Okay, I think there were some cases where it could happen that the skill menu wouldn't be regenerated for characters coming over from the old version. I've forced it to regenerate for old characters in v2.1.0, just to be sure. (changing any skill value also should solve it).

Anyway, glad you found a solution, I'm going to go ahead and close this issue, as it seems to be resolved.
