### ISSUE TITLE
Easier place to track extra effort

### ISSUE THREAD

**Issue by athedegaard** [Karlinator/roll20-character-sheets#24]
Can you add an easier way to add Effort Modifier in the sheet?  (For things like Psychic Training focus)

I'm not counting the "attributes and abilities" page, that one seems to be working but less convenient.  

Thanks!

**Comment by joesinghaus** [comment]
If you go to the settings (gear icon, top right), you can find an effort modifier.

Perhaps we should find some way to make it more obvious that this exists!

**Comment by athedegaard** [comment]
Found it, thanks!  Yes, maybe a field near the effort score for a modifier would make this easier.

Thanks for all the work you are doing on this to make an awesome game awesomer!

**Comment by joesinghaus** [comment]
We will do a more wholistic approach to modifiers in the future, then it will hopefully become easier to find.
