### ISSUE TITLE
NPC stat block: attack roll in Quick Menu not working

### ISSUE THREAD

**Issue by athedegaard** [Karlinator/roll20-character-sheets#25]
Will go through each menu option, but at end no dice get rolled.  

Thanks,
Aaron

**Comment by athedegaard** [comment]
My bad....  I think I just forgot to put in a dice value in the damage category (it still said "Weapon").  Once I changed that it seems to be working just fine.  

Chalk this one up to a bug in the space between my ears.  Thanks for looking into it, really appreciate all the work you are doing on this!

**Comment by joesinghaus** [comment]
Okay, no worries!
