### ISSUE TITLE
True AI support (Deluxe)

### ISSUE THREAD

**Issue by PanzerUXI** [Karlinator/roll20-character-sheets#26]
Couple requests for True AI Support. Definitely a down the road feature. Would have to be a setting toggle ala Space Magic. 

- Remove psionics skill names (True AI routines don't have associated skills).
- Change "Effort" to "Processing".
- Add tracking for AI Processing points (requires some way of tracking max processing nodes, ideally allow adding multiple sources since losing access to a node drops down to the next largest node you have access to).
- Replace cybernetics with integrated equipment (capacity is 2 items per level).

**Comment by PanzerUXI** [comment]
maybe merge this and transhuman & shells into one ticket?

**Comment by Karlinator** [comment]
This does share much of the rulebase with Transhuman and Shells, and it is likely that we will add them at the same time. I'm not sure about merging the issues though.

**Comment by Karlinator** [comment]
So the main things needed are bodyswapping (shared with transhuman rules) and processing.

For tracking processing, one way to go is to have a field for "internal" processing (1+wis/int by default, but plenty of cases to houserule a retech artefact somethingorother), and then a list for other nodes. These have a processing value and a "connected?" checkbox. The worker then loops through and selects the highest value that is connected, and adds internal. The rest of processing management stays the same from psionics.

**Comment by Karlinator** [comment]
Clarification: The AI has total processing equal to (highest connected node **or** 1) + wis/int + houserule/artefact/whatever.

**Comment by Karlinator** [comment]
Correction: It's 1 + max(in, wis) + max(connected nodes).

**Comment by Karlinator** [comment]
This is now implemented and will be featured in v2.5.
