### ISSUE TITLE
Sheet workers are not firing

### ISSUE THREAD

**Issue by MrFinnT** [Karlinator/roll20-character-sheets#27]
the rulebook
> Improve Saving Throws
The PC becomes more capable of evading chance harms and perils. Their saving throw scores decrease by one, making it easier to succeed on saving throws by rolling equal or over it. As a first level character has saving throw scores of 15, reaching second level would lower them to 14, modified by attributes.

but the Character Sheet does not automatically detract the Level from saving throws.
that would a be a small quality of live change

![9fde0bdbdba2168ad61456fb7e8c89e6](https://user-images.githubusercontent.com/14353237/40380454-703ce69e-5df9-11e8-8667-cfd596bb1a5d.png)

**Comment by joesinghaus** [comment]
It should do that, I'm not sure why it doesn't in your case. I presume this is a character converted from the old sheet? Try changing your level up and down, that should make the saves recalculate.

If not, please do say so, then we can look into it again.

**Comment by MrFinnT** [comment]
actually the sheet seems to be totally broken. the modifier for attributes don't change at all
not for new or old sheets. and i have no converted a sheet.
do i need to make a new game?
![d799a91d7000b6219eb963f13680aa13](https://user-images.githubusercontent.com/14353237/40384873-2167d1da-5e05-11e8-9e1d-83575d909784.png)

**Comment by joesinghaus** [comment]
Sorry, your report is correct, the sheet workers don't seem to be working at all, despite the fact that the exact same code works just fine in my test campaign. That may or may not have something to do with the fact that Roll20 forgot (?) to update the translation files this time.

Either way, I'm raising this with roll20 for investigation.

**Comment by joesinghaus** [comment]
Okay, issue resolved. Roll20 forgot to do part of their update, causing sheet workers to fail. This will be resolved by Roll20 (might take a couple hours).
