### ISSUE TITLE
Items In Weapon Section Shouldn't Always Be In Equipment

### ISSUE THREAD

**Issue by DeusExBrockina** [Karlinator/roll20-character-sheets#28]
It's convenient that items you add to the weapon section appear in the equipment section also, but it'd be nice to at least be able to delete them from the equipment section. Things like a Telekinetic's attack abilities or an unarmed attack don't belong in the equipment section.

**Comment by joesinghaus** [comment]
Thanks for the suggestion. Implemented via d68e0d1 !
