### ISSUE TITLE
Query for attribute when rolling skill set to none.

### ISSUE THREAD

**Issue by Karlinator** [Karlinator/roll20-character-sheets#32]
Rolling a skill without an attribute really doesn't happen. At all. Maybe the default "none" option should instead query for attribute (so you can set some skills that are always switching attribute to ask instead).

Alternatively, if we want to keep"none" as an option, simply make the default be "ask" and keep "none" as a separate option.

**Comment by joesinghaus** [comment]
Resolved via 272ee68. The "none" option has been renamed to "ask", and will show a query.
