### ISSUE TITLE
Permanent strain from cyberware

### ISSUE THREAD

**Issue by joesinghaus** [Karlinator/roll20-character-sheets#35]
There should be an interface for automatically adding up the permanent strain from cyberware, while still allowing people to add some more manually.

**Comment by PanzerUXI** [comment]
Feature idea to add to this - strain can be added by cyberware, healing, certain items and psionics, plus whatever homebrew stuff. Should be placed universally rather than having it logged different locations as it does currently.

**Comment by joesinghaus** [comment]
It should be noted that healing, certain items, and psionics usually add normal strain, not permanent strain. I'm not sure this actually needs to be in multiple places.

**Comment by joesinghaus** [comment]
This should be such low-hanging fruit, but it's just not easy interface-wise, at least for me.
