### ISSUE TITLE
Option to only show trained skills in quick menus

### ISSUE THREAD

**Issue by joesinghaus** [Karlinator/roll20-character-sheets#36]

**Comment by PanzerUXI** [comment]
Feature comment to this - I've had multiple players ask for some formatting in Quick Skill Menu - if its even possible 👍

**Comment by joesinghaus** [comment]
This a good addition, and indeed it looks like we could kill two birds with one stone for this.

**Comment by joesinghaus** [comment]
Closed by e9cd107.
