### ISSUE TITLE
Sheet not updating

### ISSUE THREAD

**Issue by svmnotn** [Karlinator/roll20-character-sheets#4]
I have not gotten the update to 1.4 in any of the games I'm in or in any new games I make.
Has roll20 not updated the sheets to the current master, or is it just me?

**Comment by Karlinator** [comment]
[You are indeed correct.](https://app.roll20.net/forum/post/5690522/character-sheets-delayed) The pull requests were merged in their GitHub, but they are not pushing the updated sheets until next week.

**Comment by svmnotn** [comment]
Thanks, couldn't find anything about it
