### ISSUE TITLE
Armor details

### ISSUE THREAD

**Issue by svmnotn** [Karlinator/roll20-character-sheets#40]
It would be nice if the armors section would work like the weapons section in that what is added there gets added to the gear section. Unlike weapons 0 encumbrance armor probably still should be added to the list. This would mean that we can just add the description of the armors to the gear, but if we remove the armor we don't have to remove it twice.
This is mostly good for Artifact armors that have special things about them.

**Comment by joesinghaus** [comment]
Not a bad idea, but I would actually prefer for this to be a description field in the armor section. The reason that weapons are duplicated with the gear is that the weapons section is far away from the gear section, but armor is right next to it.

**Comment by svmnotn** [comment]
Fair enough, I just want a description field for the armor. While at it, I did notice that none of the Artifacts are available, which I kinda understand for the weapons since they are whatever the GM wants them to be, but for things like the AI Companion core, or the Ghost Mantle, it would be nice to have in the auto fill.
Also the weapon's description is not added to their Gear entry even if they do have one. Not sure if that last one is intended or not.

**Comment by joesinghaus** [comment]
I made an issue for artefact autofill data: #42.
About the weapons: no, it would be intended that the description is added. Since the weapon description fields came after weapon autofill, we just forgot to do it: #43.

**Comment by svmnotn** [comment]
Cool, I'll see if I can figure out how to add those in (if it is just modifying json I should be able to do that).

So, this issue can be closed when a description field is added to the armors.

**Comment by svmnotn** [comment]
#47 adds in the descriptions, I don't know how to add the field so that is all I can do

**Comment by joesinghaus** [comment]
Adding the actual field is a bit of design process too, I'll do it in some form now.

**Comment by joesinghaus** [comment]
Closed by 8dd3fab
