### ISSUE TITLE
Add artefacts to autofill data

### ISSUE THREAD

**Issue by joesinghaus** [Karlinator/roll20-character-sheets#42]

**Comment by svmnotn** [comment]
Any preference on how to add artifact weaponry? Since they could be whichever weapon the GM decides to give out.
The artifact armor and items should be easy enough however.

**Comment by joesinghaus** [comment]
I don't have a good idea how to do artefact weapons, perhaps we should skip that for now.

**Comment by svmnotn** [comment]
Probably, I'll see about adding the armors, and items then.
