### ISSUE TITLE
Incorrect skill mod applied

### ISSUE THREAD

**Issue by Theagle43** [Karlinator/roll20-character-sheets#44]
All of the skill mods appear correctly in the character sheet itself, but when a roll is performed it's applying 1 less than the correct mod. For example, even they have no skill, it's applying -2. If they have shoot-0, it's applying -1, etc.

**Comment by Theagle43** [comment]
Update: I realized I misinterpreted the error. It's applying correctly in every situation except when firing a weapon and the skill mod should be -1, it's rolling with a -2 mod. Is this intentional?

**Comment by Theagle43** [comment]
Just read the rules. Yes, it is. I'm sorry.

**Comment by joesinghaus** [comment]
No worries :)
