### ISSUE TITLE
NPC rolling

### ISSUE THREAD

**Issue by thatguy14** [Karlinator/roll20-character-sheets#53]
Hello,

I am having an issue with the roll20 SWN revised character sheet (says 2.2.0 on the roll20 sheet). I created a new character, toggled to NPC and then filled out some information on the attacks (damage ab...). When I press the "Attacks" button in quick menus I get an error message "Unable to find a player or character with name: Jeffroy" where Jeffroy in the first part of the full name of the character sheet.

I also noticed that you can't specifically add a weapon like you can in the PC character sheet which seems like a detriment.

Thanks

**Comment by joesinghaus** [comment]
Yeah, you could fix this by using some kind of typographic quotes in the name other than standard straight double quotes. It's a roll20 limitation that's hard to overcome...
