### ISSUE TITLE
Change the `Hit Points` button to do the correct thing when the Heroic option is chosen

### ISSUE THREAD

**Issue by svmnotn** [Karlinator/roll20-character-sheets#54]
It would be nice if when the heroic option is chosen the Hit Points text button would do the correct math, as Heroic characters don't roll HP so much as just max out the dice and then half the total.

I've been using this on my campaigns:
`ceil(([[6*@{level}]] [Level] + [[@{level}*@{con_bonus}]] [Con] + [[@{level}*?{Per Level Bonus|0}]] [Bonus])/2)` so that the players don't have to do the math.

**Comment by Karlinator** [comment]
This seems to have been mostly overlooked when either Heroic support or the HP button was added. Will look into it.

**Comment by Karlinator** [comment]
Done as part of v2.4.0
