### ISSUE TITLE
HP Roll looking at wrong modifier for attributes

### ISSUE THREAD

**Issue by MaesterMarque** [Karlinator/roll20-character-sheets#60]
When clicking Hit Points on the sheet to roll for your HP, it's looking for @{con_bonus} instead of @{constitution_mod} which is listed on the sheet.

**Comment by Karlinator** [comment]
Fix'd in v2.4.1.

This only affected Heroic PCs, by the way, though it took me a few minutes to work that out and I wrote the damn thing! Apparently one of the sheets I've been testing on had a con_bonus of 1 (same as his constitution_mod) through some old leftover attributes from pre-2.0.
