### ISSUE TITLE
Consider changing the name of the `name` attribute

### ISSUE THREAD

**Issue by svmnotn** [Karlinator/roll20-character-sheets#65]
Changing the character's name attribute from `name` to `character_name` would link the character's name to that of the journal, as instructed in Roll20's [docs](https://wiki.roll20.net/Building_Character_Sheets#Character_Names)

**Comment by Karlinator** [comment]
That's probably both a good idea and easy to implement. I can't at the moment think of anything tied to the character name, so it should be completely painless.

**Comment by joesinghaus** [comment]
Related QoL improvement: watch changes to character name and replace any quotes with some kind of typographic quotes so that entering quotes does not break chat menus.

**Comment by Karlinator** [comment]
Right, because attribute values are not escaped in the roll syntax because sometimes you might want to put quotes in an attribute and have them act like quotes.
