### ISSUE TITLE
Adept Magic Effort: Daily doesn't update Uncommitted

### ISSUE THREAD

**Issue by MaesterMarque** [Karlinator/roll20-character-sheets#66]
If you update your Effort uses for the Day under space magic, it doesn't update the Uncommitted Effort, but if you edit Current Effort or Scene Effort it does, and then takes in account the Day Effort.

So, if I have 5 total Magic Effort, and I use 1 Day Effort, Uncommitted Effort remains 5.
If I then use 1 Scene effort, my Uncommitted Effort then drops to 3, one for the Scene and one for the Day.

**Comment by Karlinator** [comment]
Sounds like a missing on(change) for the committed effort day field. I'll look into it.

**Comment by Karlinator** [comment]
A stray space, which happened to align with the line break in my editor, turned out to be the culprit here.
