### ISSUE TITLE
Request: Multiple Armour fields

### ISSUE THREAD

**Issue by Laughing-Luna** [Karlinator/roll20-character-sheets#7]
Some armours can be reasonably worn under another set of armour, and some armours are only ever worn when the user is able to prepare ahead of time, whilst simultaneously wearing something more form fitting underneath.

A key example comes when wearing an artifact armour such as a Ghost Mantle under a Field Emitter Panapoly's shields.  If the FEP is offline, then the AC to check against is the Ghost Mantle's 15 instead of the FEP's 20; simultaneously, I cannot reasonably use the Ghost Mantle's stealth bonus whilst the FEP is online.

So I'd like to request that there be multiple armour fields similar to how there are multiple weapon fields to help keep quick-references handy, as well as a check box to indicate which one is active, given that Storm Armour (and therefore FEP) modifies Strength for the purposes of Encumbrance.

**Comment by joesinghaus** [comment]
Here's a question: what do to about encumbrance of non-equipped armor. Clearly, active armor adds to Readied, but where should inactive armor go (alternative: just show a select to choose this).

**Comment by Laughing-Luna** [comment]
Storm Armour specifically only modifies strength for encumbrance purposes - it will not increase your actual strength score, and FEP also specifies that it provides all the benefits of Storm Armour with no power source required.

**Comment by joesinghaus** [comment]
Okay, looks like a working solution is
CHECKED | NAME | AC | TYPE | ENCUMBRANCE (can be negative) | STATUS

Where the AC will just be the maximum of all checked ones, and type allows for selecting a shield as well, which will do the correct math for shields according to the book. Checking will automatically set the status to "readied".

**Comment by PanzerUXI** [comment]
Agreed. Looks good. Thanks Laughing.

**Comment by joesinghaus** [comment]
Closed via 204a62f.
