### ISSUE TITLE
INITITATIVE

### ISSUE THREAD

**Issue by slightlyirked** [Karlinator/roll20-character-sheets#70]
Hello, Just a small typo in the character sheet. We have been laughing about it for a few months now but rolling "INITITATIVE" for the start of combat each time is getting kind of old now :)
Thanks for the great work!

**Comment by Karlinator** [comment]
That's pretty funny. I wonder how long that's been in there; I haven't had a chance to actually use the sheet in play for several months so this could be *old*. I'll get it fixed once I get around to sorting through the merge conflict mess that I've somehow ended up with in this repo.
