### ISSUE TITLE
"No attribute was found for @{Iano Legra|name}"

### ISSUE THREAD

**Issue by Zenthran** [Karlinator/roll20-character-sheets#72]
Created a new character sheet but when trying to roll something, every time it would produce the titular error in the chat box. The roll works fine itself, but the name section of the template shows as "Iano Legra|name". I've fixed the issue by manually adding 'name' into the Abilities & Attributes section, so it functions fine now. Just thought you'd like to know that there's a bug in the sheet.

Here's what it looks like:
![failed character sheet](https://user-images.githubusercontent.com/57311761/68081738-ab628780-fe0a-11e9-8238-cd04a00d5761.png)

**Comment by joesinghaus** [comment]
Thanks for the bug report! This was introduced in v2.4.4 for new characters and is fixed in 2.4.5 next week.
