### ISSUE TITLE
UI improvement: Effort modifier not easy to find

### ISSUE THREAD

**Issue by rafjaf** [Karlinator/roll20-character-sheets#76]
Hello, 

As results from the discussions on https://github.com/Roll20/roll20-character-sheets/issues/6211, the Effort modifier is buried deep into the UI and not easy to find for people not aware of its existence... Perhaps it could be moved in the sheet itself, closer to the Efforts settings?

Thank you in any case for the excellent work done in developing this automated sheet for SWN!

**Comment by Karlinator** [comment]
Hah, the UI field was so hard to find that even the guy digging through the source code missed it.

Yeah, this is bad UX, thanks for the feedback. The intention is that if you almost never change it it doesn't need to be right up front, but it does need to be visible so relocating it to right up by the effort fields might be a good idea.

**Comment by Karlinator** [comment]
Upcoming in 2.4.8.
