### ISSUE TITLE
Drones on NPC sheet

### ISSUE THREAD

**Issue by Heartfire1123** [Karlinator/roll20-character-sheets#82]
Sorry if this isn't the place to post this.

It would be nice if there was a section on the NPC sheet that would allow you to add drones, much like you can ships. It would save the hassle of having to switch to PC mode to access them.

Thanks.

**Comment by Karlinator** [comment]
This is entirely fair, NPC's can use drones after all.

There is a whole lot of using sheet attributes in the Drones section (like Int, Pilot, etc) which need toggling to npc stats instead.
