### ISSUE TITLE
SWN only giving AI/VI character sheets

### ISSUE THREAD

**Issue by TempestWindDM** [Karlinator/roll20-character-sheets#88]
Been trying to build some test characters but have only been receiving sheets for AI/VI

**Comment by Karlinator** [comment]
Thanks, found the issue. I have a fix coming, but in the mean time here's a workaround: Toggle and untoggle the options for both Transhuman and AI. This should make the sheet go back to normal.

**Comment by TempestWindDM** [comment]
Thanks

**Comment by Karlinator** [comment]
Fix is now deployed!
