### ISSUE TITLE
Add support for specifying the WWN skill list before launching the game

### ISSUE THREAD

**Issue by eehlers** [Karlinator/roll20-character-sheets#97]
Before I launch my game, if I go into Settings, Game Settings, I see a label Skill List for a drop down containing the values Revised Edition, First Edition, Neither.

If I launch the game and add a character, then in the settings for that character sheet, I see a label Skill List for a drop down containing the values Revised Edition, First Edition, Worlds Without Number, Neither.

Would it be possible to extend that first drop down to include the value Worlds Without Number?

**Comment by Karlinator** [comment]
Yup, I'll add that. Simple oversight when I added the skill list. Thanks!

**Comment by Karlinator** [comment]
Fixed in v2.5.4
