### ISSUE TITLE
Quick Menus: "Unrecognised command: /w"

### ISSUE THREAD

**Issue by SeanStrain** [Karlinator/roll20-character-sheets#98]
The Quick Menu buttons the Stars Without Number Revised Character Sheets on both PC and NPC sheets do not function, instead clicking on them will publish the error "Unrecognised command: /w" to the chat log.

**Comment by Karlinator** [comment]
Issue reproduced. Initiative works, but nothing else. Looks like some disagreement between my sheet and Roll20 on chat commands. Will look into it.
